### ISSUE TITLE
Include Darwin arm64 builds in the NPM package

### ISSUE THREAD

**Issue by Arden144** [rescript-association/reanalyze#189]
Right now both the VSCode extension for ReScript and the NPM reanalyze package don't have any executables for arm64 devices

**Comment by cristianoc** [comment]
This should be doable following what the compiler does.
CC @cknitt

**Comment by cknitt** [comment]
It seem the rescript-vscode CI already builds the ARM64 binary?
https://github.com/rescript-lang/rescript-vscode/blob/dab2a95ae760d2a0f942348125664fc855b6b340/.github/workflows/ci.yml#L23

For this repo (reanalyze), the problem is that the ARM64 runner on our Mac Mini M1 is only added to the rescript-lang organization, not the rescript-association organization. (To make it availabe for the rescript-association organization, we would need to start a second runner instance on that machine which I would like to avoid.)

**Comment by cristianoc** [comment]
Sorry I did not pay attention this is the reanalyze project.
Should update the readme.
Development has moved inside the vscode extension.
This repo is for use with opam.

**Comment by Arden144** [comment]
> It seem the rescript-vscode CI already builds the ARM64 binary? https://github.com/rescript-lang/rescript-vscode/blob/dab2a95ae760d2a0f942348125664fc855b6b340/.github/workflows/ci.yml#L23
> 
> For this repo (reanalyze), the problem is that the ARM64 runner on our Mac Mini M1 is only added to the rescript-lang organization, not the rescript-association organization. (To make it availabe for the rescript-association organization, we would need to start a second runner instance on that machine which I would like to avoid.)

My apologies for opening an issue in the wrong repo. I looked at the extension and it looks like it does build and ship an arm64 binary, but the extension code uses the wrong binary. I'll open an issue on the extension repo
